
[
    {
        "card_number": 7,
        "category": "Macro Indicators",
        "term": "PMI",
        "full_name": "Purchasing Managers' Index",
        "definition": "PMI surveys purchasing managers at hundreds of companies, asking whether activity — new orders, production, employment, deliveries — is expanding, contracting, or unchanged versus the prior month.",
        "context": "PMI is released on the first business day of each month — making it one of the earliest reads on economic momentum. Because it's a survey, it reflects expectations and intentions, not just lagging results.",
        "frequency": "Published: Monthly (1st business day)",
        "trend": "down",
        "trend_label": "↓ Contracting",
        "formula": "Above 50 → sector is expanding\
Below 50 → sector is contracting\
Two separate indexes: Manufacturing PMI and Services PMI",
        "current_value": "49.0",
        "current_value_period": "Feb 2026 · Below 50",
        "current_value_color": "red",
        "chart_label": "ISM Manufacturing PMI — Monthly (50 = breakeven)",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "Services PMI",
        "stat1_value": "53.5",
        "stat1_sub": "Expanding · Feb 2026",
        "stat1_color": "green",
        "stat2_label": "Expansion Line",
        "stat2_value": "50.0",
        "stat2_sub": "Above = growth",
        "stat2_color": "gray",
        "insight": "Manufacturing dipped back below 50 — a contraction signal — but services at 53.5 are keeping the broader economy afloat. Since services dominate the U.S. economy (~80% of GDP), a strong services PMI matters more for overall growth than a weak factory reading.",
        "source": "Institute for Supply Management",
        "back_source_label": "Latest Data · ISM",
        "back_title": "Manufacturing PMI — Current"
    },
    {
        "card_number": 8,
        "category": "Inflation",
        "term": "PPI",
        "full_name": "Producer Price Index",
        "definition": "PPI measures the average change in prices that domestic producers receive for their output — raw materials, intermediate goods, and finished products. It's CPI's upstream cousin: what businesses pay before consumers do.",
        "context": "PPI is considered a leading indicator for consumer inflation. When input costs rise for producers, those costs typically get passed downstream to consumers within 1–3 months.",
        "frequency": "Published: Monthly",
        "trend": "up",
        "trend_label": "↑ Rising",
        "formula": "PPI rising → production costs climbing → CPI likely to follow\
PPI falling → deflationary pressure building upstream",
        "current_value": "3.5%",
        "current_value_period": "YoY · Jan 2026",
        "current_value_color": "red",
        "chart_label": "PPI Final Demand YoY — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "Core PPI",
        "stat1_value": "3.6%",
        "stat1_sub": "Excl. food, energy & trade",
        "stat1_color": "red",
        "stat2_label": "vs CPI Gap",
        "stat2_value": "+0.4%",
        "stat2_sub": "PPI above CPI → pressure",
        "stat2_color": "red",
        "insight": "PPI running above CPI signals that producers are absorbing some cost increases rather than fully passing them on — that margin compression often shows up in earnings misses. If producers start passing costs through, CPI could re-accelerate in coming months.",
        "source": "U.S. Bureau of Labor Statistics",
        "back_source_label": "Latest Data · BLS",
        "back_title": "PPI — Current Trend"
    },
    {
        "card_number": 9,
        "category": "Markets",
        "term": "VIX",
        "full_name": "CBOE Volatility Index",
        "definition": "The VIX measures the market's expectation of S&P 500 volatility over the next 30 days, derived from the prices of S&P 500 options. It is widely called the \"fear gauge\" of Wall Street.",
        "context": "VIX and the S&P 500 tend to move inversely — when stocks fall, VIX spikes. Savvy investors watch VIX for timing: extreme VIX spikes often mark capitulation lows, while extremely low VIX can signal complacency.",
        "frequency": "Updated: Continuously (market hours)",
        "trend": "up",
        "trend_label": "↑ Elevated",
        "formula": "VIX < 15 → calm, complacent market\
VIX 15–25 → moderate uncertainty\
VIX > 30 → elevated fear / market stress\
VIX > 40 → crisis-level panic (seen in 2008, 2020)",
        "current_value": "22.3",
        "current_value_period": "Mar 2026 · Elevated",
        "current_value_color": "red",
        "chart_label": "VIX Month-End Close — Recent",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "Historical Average",
        "stat1_value": "~19",
        "stat1_sub": "Long-run mean",
        "stat1_color": "gray",
        "stat2_label": "Fear Threshold",
        "stat2_value": "20+",
        "stat2_sub": "Currently above",
        "stat2_color": "red",
        "insight": "VIX above 20 signals elevated market anxiety — not panic, but meaningful near-term uncertainty. For long-term ETF holders, elevated VIX can be an opportunity to add to positions at better prices, as vol spikes often overshoot and revert. Avoid reactionary selling.",
        "source": "CBOE",
        "back_source_label": "Latest Data · CBOE",
        "back_title": "VIX — Current Level"
    },
    {
        "card_number": 10,
        "category": "Trade & FX",
        "term": "DXY",
        "full_name": "U.S. Dollar Index",
        "definition": "DXY measures the value of the U.S. dollar against a basket of six major currencies — primarily the Euro (57.6%), Japanese Yen (13.6%), British Pound (11.9%), and three others. A higher DXY means a stronger dollar.",
        "context": "DXY is the global benchmark for dollar strength. It influences commodities (most priced in USD), emerging markets (dollar-denominated debt becomes harder to service), and multinational corporate earnings.",
        "frequency": "Updated: Continuously (forex hours)",
        "trend": "down",
        "trend_label": "↓ Weakening",
        "formula": "Strong dollar → U.S. imports cheaper · exports more expensive · foreign earnings worth less in USD\
Weak dollar → exports competitive · international ETFs get a currency boost",
        "current_value": "98.8",
        "current_value_period": "Mar 2026 · Multi-month low",
        "current_value_color": "green",
        "chart_label": "DXY Month-End Close — Recent",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "EUR/USD",
        "stat1_value": "1.073",
        "stat1_sub": "Euro strengthening",
        "stat1_color": "green",
        "stat2_label": "52-Week Range",
        "stat2_value": "98.5–108",
        "stat2_sub": "Near range low",
        "stat2_color": "gray",
        "insight": "A weakening dollar is a tailwind for international ETFs (EFA, VEA, EEM) — foreign gains translate into more USD when you convert back. It also boosts commodity prices and eases pressure on emerging-market dollar-denominated debt. Watch for dollar stabilization if the Fed pauses cuts.",
        "source": "ICE / FRED",
        "back_source_label": "Latest Data · ICE / FRED",
        "back_title": "U.S. Dollar Index — Current"
    },
    {
        "card_number": 11,
        "category": "Employment",
        "term": "JOLTS",
        "full_name": "Job Openings & Labor Turnover Survey",
        "definition": "JOLTS counts how many job openings exist across the U.S. economy at month-end, plus how many workers were hired, quit, or laid off. It paints a picture of labor market dynamics, not just the headline count.",
        "context": "Fed Chair Powell watches JOLTS closely. When workers quit readily, it means they're confident they can find better jobs — a sign of a hot labor market that could sustain wage inflation.",
        "frequency": "Published: Monthly (2-month lag)",
        "trend": "down",
        "trend_label": "↓ Cooling",
        "formula": "Key ratio: Job Openings ÷ Unemployed Workers\
Ratio > 1.0 → more jobs than people looking → tight market\
The \"Quits Rate\" — voluntary resignations — is the Fed's favorite confidence gauge",
        "current_value": "7.7M",
        "current_value_period": "Dec 2025",
        "current_value_color": "red",
        "chart_label": "Job Openings (millions) — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "Quits Rate",
        "stat1_value": "2.0%",
        "stat1_sub": "↓ from 2.4% peak",
        "stat1_color": "red",
        "stat2_label": "Openings per Unemployed",
        "stat2_value": "1.4×",
        "stat2_sub": "Still above 1:1",
        "stat2_color": "blue",
        "insight": "The quits rate at 2.0% — down from a 2.4% peak — signals workers feel less confident about jumping to new jobs. This reduces wage growth pressure, which is exactly what the Fed wants to see before cutting rates. A soft landing means openings cool gradually, not collapse.",
        "source": "U.S. Bureau of Labor Statistics",
        "back_source_label": "Latest Data · BLS",
        "back_title": "JOLTS Job Openings — Current"
    },
    {
        "card_number": 12,
        "category": "Employment",
        "term": "Claims",
        "full_name": "Initial Jobless Claims (Weekly)",
        "definition": "Initial jobless claims counts the number of Americans who filed for unemployment benefits for the first time in a given week. It's the most timely labor market indicator available — data is just one week old.",
        "context": "Released every Thursday morning, claims move markets immediately. The 4-week moving average smooths out holiday noise and weather distortions — it's the number economists focus on, not the weekly print.",
        "frequency": "Published: Weekly (every Thursday)",
        "trend": "flat",
        "trend_label": "→ Stable",
        "formula": "< 250K/week → healthy labor market\
250–350K → softening, watch closely\
> 350K sustained → recession-level job losses",
        "current_value": "220K",
        "current_value_period": "Week of Mar 1, 2026",
        "current_value_color": "green",
        "chart_label": "Weekly Initial Claims — Last 4 Weeks",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "4-Week Average",
        "stat1_value": "219K",
        "stat1_sub": "Historically low",
        "stat1_color": "green",
        "stat2_label": "Recession Threshold",
        "stat2_value": "350K+",
        "stat2_sub": "Far from danger zone",
        "stat2_color": "gray",
        "insight": "Claims near 220K remain historically low — the labor market isn't cracking. As long as claims stay below 250K, the economy is generating more jobs than it's losing. Watch for sustained moves above 260–280K as an early warning signal worth acting on.",
        "source": "U.S. Dept. of Labor",
        "back_source_label": "Latest Data · DOL",
        "back_title": "Initial Claims — Current"
    },
    {
        "card_number": 13,
        "category": "Macro Indicators",
        "term": "Retail Sales",
        "full_name": "U.S. Advance Retail Sales (MoM)",
        "definition": "Retail Sales measures total receipts at stores that sell consumer goods — from auto dealers to online retailers to gas stations. It is the most direct monthly read on consumer spending, which drives ~70% of U.S. GDP.",
        "context": "Because consumer spending is the economy's engine, retail sales moves can shift Fed expectations instantly. A sustained softening signals demand destruction; a rebound signals resilience.",
        "frequency": "Published: Monthly (~mid-month)",
        "trend": "flat",
        "trend_label": "→ Mixed",
        "formula": "Reported month-over-month (MoM) — a positive print means consumers spent more\
\"Control group\" (ex-auto, gas, building materials) is what flows directly into GDP calculations",
        "current_value": "+0.2%",
        "current_value_period": "Jan 2026",
        "current_value_color": "blue",
        "chart_label": "Retail Sales MoM % Change — Recent",
        "chart_type": "bar_sign",
        "chart_data": None,
        "stat1_label": "Ex-Auto & Gas",
        "stat1_value": "+0.8%",
        "stat1_sub": "Core strength",
        "stat1_color": "green",
        "stat2_label": "Consumer Share of GDP",
        "stat2_value": "~70%",
        "stat2_sub": "Economy's engine",
        "stat2_color": "gray",
        "insight": "December's −0.9% was weather and post-holiday payback; January's modest rebound signals consumers are still spending — just cautiously. The ex-auto control group at +0.8% is the cleanest signal of underlying demand. Consumer resilience supports earnings for discretionary and retail ETFs.",
        "source": "U.S. Census Bureau",
        "back_source_label": "Latest Data · Census Bureau",
        "back_title": "Retail Sales MoM — Current"
    },
    {
        "card_number": 14,
        "category": "Macro Indicators",
        "term": "Housing Starts",
        "full_name": "New Residential Construction (Annualized)",
        "definition": "Housing Starts counts the number of new residential construction projects begun in a given month, reported as an annualized rate. It measures the pulse of homebuilding activity across the U.S.",
        "context": "Housing is one of the most interest-rate-sensitive sectors in the economy. When rates rise, starts fall; when rates fall, starts recover. Watching housing starts tells you whether rate policy is actually filtering through to the real economy.",
        "frequency": "Published: Monthly (~3rd week)",
        "trend": "down",
        "trend_label": "↓ Subdued",
        "formula": "Starts > 1.5M annualized → healthy construction pace\
Building Permits (released same day) lead Starts by 1–2 months\
Highly sensitive to mortgage rates — the rate-cut barometer",
        "current_value": "1.37M",
        "current_value_period": "Jan 2026 · Annualized",
        "current_value_color": "red",
        "chart_label": "Housing Starts (millions, annualized) — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "Building Permits",
        "stat1_value": "1.48M",
        "stat1_sub": "Leading indicator",
        "stat1_color": "blue",
        "stat2_label": "30Y Mortgage Rate",
        "stat2_value": "6.9%",
        "stat2_sub": "Constraining demand",
        "stat2_color": "red",
        "insight": "Housing is stuck — constrained by 6.9% mortgage rates that keep both builders and buyers cautious. A meaningful recovery needs the 10Y Treasury to fall toward 3.5–4.0%. When housing starts recover, it will confirm that Fed rate cuts are working — a bullish signal for homebuilder and REIT ETFs.",
        "source": "U.S. Census Bureau / HUD",
        "back_source_label": "Latest Data · Census Bureau / HUD",
        "back_title": "Housing Starts — Current"
    },
    {
        "card_number": 15,
        "category": "Markets",
        "term": "Credit Spreads",
        "full_name": "High Yield & Investment Grade Bond Spreads",
        "definition": "A credit spread is the extra yield investors demand on corporate bonds above equivalent U.S. Treasury yields. It represents the price of default risk — how much extra return the market requires to lend to companies instead of the government.",
        "context": "Credit spreads widen before recessions as investors price in rising default risk. They are a leading indicator of financial stress — often signaling trouble before it shows up in GDP or unemployment data.",
        "frequency": "Updated: Daily",
        "trend": "up",
        "trend_label": "↑ Widening",
        "formula": "Tight spreads (<300 bps HY) → market calm, credit conditions easy\
Wide spreads (>500 bps HY) → stress, tightening financial conditions\
IG spreads typically run 80–150 bps; HY spreads 250–600 bps in normal cycles",
        "current_value": "380 bps",
        "current_value_period": "Mar 2026 · Widening",
        "current_value_color": "red",
        "chart_label": "High Yield OAS — Monthly (basis points)",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "IG Spread",
        "stat1_value": "105 bps",
        "stat1_sub": "Investment grade",
        "stat1_color": "blue",
        "stat2_label": "Historical HY Avg",
        "stat2_value": "~400 bps",
        "stat2_sub": "Near average now",
        "stat2_color": "gray",
        "insight": "Spreads widening to 380 bps signals rising corporate stress — but still below the ~500 bps level that historically precedes recessions. For ETF investors, widening HY spreads are a reason to reduce exposure to junk bond funds (HYG, JNK) and favor investment-grade or Treasury ETFs until the trend reverses.",
        "source": "ICE BofA / FRED",
        "back_source_label": "Latest Data · ICE BofA / FRED",
        "back_title": "HY Credit Spread — Current"
    },
    {
        "card_number": 16,
        "category": "Central Banks",
        "term": "Real Rate",
        "full_name": "Real Interest Rate (FFR minus Core PCE)",
        "definition": "The real interest rate strips out inflation from the nominal rate, showing what borrowers and savers actually earn or pay in purchasing-power terms. It tells you whether monetary policy is truly restrictive or just nominally high.",
        "context": "During 2022–23, the Fed raised the FFR sharply while inflation ran above it — keeping the real rate negative and policy looser than it appeared. Only when the FFR exceeded inflation did policy become truly restrictive. The neutral real rate is estimated at ~0.5%.",
        "frequency": "Derived: Monthly (FFR − Core PCE)",
        "trend": "flat",
        "trend_label": "→ Elevated",
        "formula": "Real Rate = Nominal Rate − Inflation (Core PCE)\
Positive real rate → policy is genuinely restrictive\
Negative real rate → policy is stimulative (money is \"cheap\")",
        "current_value": "+1.58%",
        "current_value_period": "Jan 2026 · Restrictive",
        "current_value_color": "red",
        "chart_label": "Rate Decomposition — Jan 2026",
        "chart_type": "none",
        "chart_data": None,
        "stat1_label": "Neutral Real Rate",
        "stat1_value": "~0.5%",
        "stat1_sub": "Fed's r-star estimate",
        "stat1_color": "gray",
        "stat2_label": "Policy Stance",
        "stat2_value": "Restrictive",
        "stat2_sub": "+1.08% above neutral",
        "stat2_color": "red",
        "insight": "A real rate of +1.58% — well above the neutral ~0.5% — means policy is genuinely restrictive: borrowing is expensive in real terms, suppressing investment and spending. As inflation falls or the Fed cuts, the real rate will ease — that's the moment to expect a broader risk-asset rally and recovery in rate-sensitive sectors.",
        "source": "Federal Reserve / BEA",
        "back_source_label": "Derived · Fed / BEA",
        "back_title": "Real Interest Rate — Current"
    },
    {
        "card_number": 17,
        "category": "Macro Indicators",
        "term": "Consumer Confidence",
        "full_name": "Conference Board Consumer Confidence Index",
        "definition": "The Conference Board surveys ~3,000 households monthly, asking how they feel about current business conditions, the job market, and their expectations six months ahead. It produces an index benchmarked to 100 (1985 baseline).",
        "context": "Consumer confidence drives spending, which drives ~70% of GDP. When it falls sharply, watch retail and consumer discretionary ETFs. The gap between Present Situation and Expectations is often more revealing than the headline number.",
        "frequency": "Published: Monthly (last Tuesday)",
        "trend": "down",
        "trend_label": "↓ Declining",
        "formula": "Two components:\
Present Situation Index — how things feel right now\
Expectations Index — outlook for jobs and income in 6 months\
When Present > Expectations: consumers confident today but worried about tomorrow",
        "current_value": "98.3",
        "current_value_period": "Feb 2026",
        "current_value_color": "red",
        "chart_label": "Consumer Confidence Index — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "Present Situation",
        "stat1_value": "138.1",
        "stat1_sub": "Conditions feel good",
        "stat1_color": "green",
        "stat2_label": "Expectations",
        "stat2_value": "72.9",
        "stat2_sub": "Worried about future",
        "stat2_color": "red",
        "insight": "The Present–Expectations gap is wide: consumers feel fine today but are anxious about the next 6 months. This divergence often precedes a pullback in discretionary spending. Watch consumer staples ETFs (XLP) as a defensive tilt when confidence drops sharply.",
        "source": "Conference Board",
        "back_source_label": "Latest Data · Conference Board",
        "back_title": "Consumer Confidence — Current"
    },
    {
        "card_number": 18,
        "category": "Macro Indicators",
        "term": "Michigan Sentiment",
        "full_name": "University of Michigan Consumer Sentiment Index",
        "definition": "The U of Michigan surveys ~500 households twice a month, measuring how Americans feel about their personal finances, buying conditions, and economic outlook. Released in preliminary and final form, it is the Fed's preferred sentiment gauge.",
        "context": "Unlike the Conference Board's measure, Michigan captures inflation psychology directly. When consumers expect high inflation, they demand higher wages and spend faster — creating the very inflation they fear. The Fed watches this feedback loop carefully.",
        "frequency": "Published: Monthly (preliminary & final)",
        "trend": "down",
        "trend_label": "↓ Declining",
        "formula": "Index range: 0–100 (1964 baseline = 100)\
Includes a crucial sub-measure: 1-year and 5-year inflation expectations\
Fed watches these expectations closely — if they become \"unanchored,\" the Fed must act",
        "current_value": "71.8",
        "current_value_period": "Feb 2026",
        "current_value_color": "red",
        "chart_label": "Michigan Sentiment Index — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "1-Year Inflation Expectation",
        "stat1_value": "2.8%",
        "stat1_sub": "Slightly above 2% target",
        "stat1_color": "red",
        "stat2_label": "5-Year Inflation Expectation",
        "stat2_value": "2.5%",
        "stat2_sub": "Anchored but rising",
        "stat2_color": "blue",
        "insight": "Michigan sentiment has fallen sharply from above 80 a year ago — consumers are genuinely worried about future inflation and earnings resilience. The 1-year inflation expectation at 2.8% is inching up, which is why the Fed remains cautious about cutting rates aggressively. Watch for further deterioration in the \"expectations\" component as a recession warning.",
        "source": "University of Michigan",
        "back_source_label": "Latest Data · U of Michigan",
        "back_title": "Michigan Sentiment — Current"
    },
    {
        "card_number": 19,
        "category": "Macro Indicators",
        "term": "Industrial Production",
        "full_name": "Industrial Production & Capacity Utilization (Fed)",
        "definition": "Industrial Production measures the real output of manufacturing, mining, and utilities sectors — the \"physical economy\" that makes goods. Released monthly by the Federal Reserve, it's one of the four indicators the NBER uses to date recessions.",
        "context": "As the U.S. economy shifted to services, IP covers roughly 20% of GDP — but it's a leading indicator of business investment and hiring cycles in goods-producing industries, which punch above their weight in economic cycles.",
        "frequency": "Published: Monthly (~mid-month)",
        "trend": "flat",
        "trend_label": "→ Mixed",
        "formula": "Paired with Capacity Utilization: how much of the economy's factory capacity is in use\
Utilization > 80% → inflationary pressure (economy running hot)\
Utilization < 77% → slack exists, no inflation pressure",
        "current_value": "−0.1%",
        "current_value_period": "Jan 2026",
        "current_value_color": "red",
        "chart_label": "Industrial Production % Change MoM — Recent",
        "chart_type": "bar_sign",
        "chart_data": None,
        "stat1_label": "Capacity Utilization",
        "stat1_value": "77.1%",
        "stat1_sub": "Below 80% = no overheating",
        "stat1_color": "blue",
        "stat2_label": "Mfg Output",
        "stat2_value": "+0.1%",
        "stat2_sub": "Slight positive",
        "stat2_color": "blue",
        "insight": "The January dip follows December's utilities surge — not a trend reversal. Capacity at 77.1% shows slack in the industrial economy, which is disinflationary — good for inflation expectations but suggests limited upside for industrial and materials ETFs (XLI, XLB) until demand accelerates.",
        "source": "Federal Reserve",
        "back_source_label": "Latest Data · Federal Reserve",
        "back_title": "Industrial Production MoM — Current"
    },
    {
        "card_number": 20,
        "category": "Macro Indicators",
        "term": "Durable Goods",
        "full_name": "Durable Goods Orders (Advance Estimate)",
        "definition": "Durable Goods Orders measures new orders placed with U.S. manufacturers for items expected to last three or more years — aircraft, machinery, computers, autos, appliances. It's a forward-looking gauge of business investment intentions.",
        "context": "The \"core capital goods\" sub-component is what economists watch most closely — it captures whether businesses are ordering new equipment and machinery, a forward signal for productivity and growth.",
        "frequency": "Published: Monthly (~4th week)",
        "trend": "flat",
        "trend_label": "→ Mixed",
        "formula": "Headline: total durable goods orders (volatile — dominated by aircraft)\
Core: ex-transportation = steadier read\
Core Capital Goods (ex-defense, ex-aircraft) = best proxy for business investment plans",
        "current_value": "+3.1%",
        "current_value_period": "Jan 2026 · Headline",
        "current_value_color": "green",
        "chart_label": "Durable Goods Orders % Change MoM — Recent",
        "chart_type": "bar_sign",
        "chart_data": None,
        "stat1_label": "Ex-Transportation",
        "stat1_value": "−0.3%",
        "stat1_sub": "Underlying soft",
        "stat1_color": "red",
        "stat2_label": "Core Capital Goods",
        "stat2_value": "+0.1%",
        "stat2_sub": "Business investment flat",
        "stat2_color": "blue",
        "insight": "The +3.1% headline surge was almost entirely Boeing aircraft orders — highly volatile, not repeatable. Strip that out and the picture is flat. Businesses aren't ramping capital investment yet, which limits upside for industrials ETFs but also means the economy isn't overheating.",
        "source": "U.S. Census Bureau",
        "back_source_label": "Latest Data · Census Bureau",
        "back_title": "Durable Goods Orders MoM — Current"
    },
    {
        "card_number": 21,
        "category": "Inflation",
        "term": "Breakeven Inflation",
        "full_name": "10-Year TIPS Breakeven Inflation Rate",
        "definition": "The breakeven inflation rate is what the bond market expects average annual inflation to be over the next 10 years. It's derived from the yield difference between regular Treasury bonds and TIPS (Treasury Inflation-Protected Securities).",
        "context": "Unlike CPI or PCE, which measure inflation that has already happened, breakeven inflation shows what the market expects. It's a real-time signal watched by every fixed-income investor and Fed official daily.",
        "frequency": "Updated: Daily",
        "trend": "up",
        "trend_label": "↑ Rising",
        "formula": "Breakeven Rate = 10Y Nominal Treasury Yield − 10Y TIPS Real Yield\
If breakeven > Fed's 2% target → market doubts the Fed can hit its target\
If breakeven < 2% → market expects below-target inflation",
        "current_value": "2.31%",
        "current_value_period": "Mar 2026",
        "current_value_color": "red",
        "chart_label": "10-Year TIPS Breakeven — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "5-Year Breakeven",
        "stat1_value": "2.48%",
        "stat1_sub": "Near-term expectations higher",
        "stat1_color": "red",
        "stat2_label": "Fed Target",
        "stat2_value": "2.0%",
        "stat2_sub": "Both above target",
        "stat2_color": "gray",
        "insight": "With breakevens rising above 2.3%, bond markets are signaling that inflation will stay above target for the next decade. This reduces the case for rate cuts and keeps pressure on long-duration bonds (TLT). TIPS themselves become attractive when breakevens are rising — they pay out more as inflation rises.",
        "source": "FRED / U.S. Treasury",
        "back_source_label": "Latest Data · FRED / U.S. Treasury",
        "back_title": "10Y Breakeven — Current"
    },
    {
        "card_number": 22,
        "category": "Inflation",
        "term": "Import Prices",
        "full_name": "U.S. Import & Export Price Index (BLS)",
        "definition": "Import prices track how much U.S. businesses pay for goods purchased from abroad — everything from foreign electronics and clothing to oil and pharmaceuticals. Rising import prices mean inflation is being \"imported\" into the domestic economy.",
        "context": "With sweeping new tariffs in effect, import prices have become one of the most watched inflation gauges of 2025–26. The BLS releases both import and export price indexes together monthly.",
        "frequency": "Published: Monthly",
        "trend": "up",
        "trend_label": "↑ Rising",
        "formula": "Import Price Index → feeds into PPI within ~1 month → feeds into CPI within ~2–3 months\
Key driver: tariffs are import price increases by definition — a 10% tariff = 10% import price shock on affected goods",
        "current_value": "+0.4%",
        "current_value_period": "Jan 2026 · MoM",
        "current_value_color": "red",
        "chart_label": "Import Prices % Change MoM — Recent",
        "chart_type": "bar_sign",
        "chart_data": None,
        "stat1_label": "YoY Import Prices",
        "stat1_value": "+2.2%",
        "stat1_sub": "Accelerating",
        "stat1_color": "red",
        "stat2_label": "Ex-Petroleum",
        "stat2_value": "+1.8%",
        "stat2_sub": "Tariff impact visible",
        "stat2_color": "red",
        "insight": "Rising import prices — partly tariff-driven — feed into producer and consumer prices within months. This is a second-wave inflation risk: even if demand is cooling, cost-push inflation from tariffs can keep CPI elevated regardless. Companies with heavy import exposure (retail, consumer goods) face margin pressure.",
        "source": "U.S. Bureau of Labor Statistics",
        "back_source_label": "Latest Data · BLS",
        "back_title": "Import Prices MoM — Current"
    },
    {
        "card_number": 23,
        "category": "Inflation",
        "term": "Income & Spending",
        "full_name": "Personal Income & Personal Consumption Expenditures (BEA)",
        "definition": "The BEA's monthly Personal Income and Outlays report tracks how much Americans earned and spent. It's released on the same day as PCE — in fact, PCE inflation is derived from this same data. Together they tell the full consumer story.",
        "context": "When income growth outpaces spending, consumers are building a cushion — a healthy dynamic. When spending outpaces income, it signals either credit-fueled consumption or savings depletion, both of which are unsustainable.",
        "frequency": "Published: Monthly (last Friday)",
        "trend": "flat",
        "trend_label": "→ Mixed",
        "formula": "Personal Income growth > Spending growth → savings rate rises → disinflationary\
Spending growth > Income growth → consumers drawing down savings → unsustainable\
Personal Savings Rate = (Income − Spending) / Income",
        "current_value": "+0.2%",
        "current_value_period": "Jan 2026 · Spending MoM",
        "current_value_color": "blue",
        "chart_label": "Personal Spending % Change MoM — Recent",
        "chart_type": "bar_sign",
        "chart_data": None,
        "stat1_label": "Personal Income MoM",
        "stat1_value": "+0.9%",
        "stat1_sub": "Strong — income > spending",
        "stat1_color": "green",
        "stat2_label": "Personal Savings Rate",
        "stat2_value": "4.6%",
        "stat2_sub": "Rebuilding buffers",
        "stat2_color": "green",
        "insight": "Income growing faster than spending is a disinflationary signal — consumers are saving, not splurging. The savings rate tick-up to 4.6% shows resilience, not distress. This dynamic supports a soft landing and allows the Fed room to cut without reigniting demand-driven inflation.",
        "source": "U.S. Bureau of Economic Analysis",
        "back_source_label": "Latest Data · BEA",
        "back_title": "Personal Spending MoM — Current"
    },
    {
        "card_number": 24,
        "category": "Employment",
        "term": "U-6",
        "full_name": "Broad (Real) Unemployment Rate",
        "definition": "U-6 is the broadest official measure of unemployment. It counts not just the jobless (U-3 headline rate), but also discouraged workers who've stopped looking and people working part-time who want full-time work. It reveals labor market slack hidden in the headline.",
        "context": "When the U-6/U-3 gap widens, it means more people are working below their capacity — a sign of a cooling labor market even when the headline looks healthy. The Fed watches this to gauge true wage pressure potential.",
        "frequency": "Published: Monthly (alongside NFP)",
        "trend": "up",
        "trend_label": "↑ Rising",
        "formula": "U-3 (Headline): Unemployed ÷ Labor Force\
U-6 (Broad): (Unemployed + Marginally Attached + Part-Time for Economic Reasons) ÷ Labor Force\
Gap between U-6 and U-3 = degree of underemployment in the economy",
        "current_value": "8.0%",
        "current_value_period": "Feb 2026",
        "current_value_color": "red",
        "chart_label": "U-6 Broad Unemployment Rate — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "U-3 Headline",
        "stat1_value": "4.1%",
        "stat1_sub": "Looks healthy…",
        "stat1_color": "blue",
        "stat2_label": "U-6 / U-3 Gap",
        "stat2_value": "3.9 pts",
        "stat2_sub": "Widening — more slack",
        "stat2_color": "red",
        "insight": "U-6 rising to 8.0% while U-3 holds at 4.1% means the gap is widening — more workers are stuck in part-time or marginally attached situations. This signals more labor market slack than the headline implies, which is actually good for inflation control but bad for consumer spending power and wage growth momentum.",
        "source": "U.S. Bureau of Labor Statistics",
        "back_source_label": "Latest Data · BLS",
        "back_title": "U-6 Unemployment — Current"
    },
    {
        "card_number": 25,
        "category": "Employment",
        "term": "LFPR",
        "full_name": "Labor Force Participation Rate",
        "definition": "LFPR is the percentage of the civilian non-institutional population (age 16+) that is either employed or actively looking for work. It measures how much of America's potential workforce is actually in the labor market.",
        "context": "The U.S. LFPR peaked at 67.3% in early 2000, dropped post-2008, and fell further during COVID. Its recovery is a long-term structural story — aging demographics make a full return to pre-2000 levels unlikely.",
        "frequency": "Published: Monthly (alongside NFP)",
        "trend": "down",
        "trend_label": "↓ Declining",
        "formula": "LFPR = Labor Force ÷ Civilian Non-Institutional Population × 100\
Declining LFPR → workers leaving workforce → unemployment rate falls \"artificially\"\
Prime-Age LFPR (25–54 year olds) = cleanest signal, less affected by aging demographics",
        "current_value": "62.6%",
        "current_value_period": "Feb 2026",
        "current_value_color": "red",
        "chart_label": "Labor Force Participation Rate — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "Pre-Pandemic Peak",
        "stat1_value": "63.4%",
        "stat1_sub": "Still below Feb 2020",
        "stat1_color": "gray",
        "stat2_label": "Prime-Age LFPR",
        "stat2_value": "83.7%",
        "stat2_sub": "Near pre-pandemic high",
        "stat2_color": "green",
        "insight": "The overall LFPR drag is mostly demographic — retiring boomers, not discouraged workers. Prime-age LFPR at 83.7% is nearly fully recovered. This distinction matters: if prime-age workers are participating, the labor supply is healthy; the headline decline isn't a crisis signal but a structural demographic reality.",
        "source": "U.S. Bureau of Labor Statistics",
        "back_source_label": "Latest Data · BLS",
        "back_title": "Labor Force Participation — Current"
    },
    {
        "card_number": 26,
        "category": "Central Banks",
        "term": "Dot Plot",
        "full_name": "FOMC Summary of Economic Projections (SEP)",
        "definition": "Four times a year, each of the 18 FOMC members submits their anonymous projection for where the Federal Funds Rate should be at year-end. Plotted as dots on a chart, this \"dot plot\" gives markets a direct window into Fed thinking on the rate path.",
        "context": "Markets move sharply when the median dot shifts. A \"hawkish dot plot\" (fewer cuts than expected) sends bond yields up; a \"dovish\" one (more cuts) rallies bonds and growth stocks. It's released quarterly alongside the Fed's economic forecasts.",
        "frequency": "Published: Quarterly (Mar, Jun, Sep, Dec)",
        "trend": "flat",
        "trend_label": "→ 2 Cuts in 2026",
        "formula": "Median dot = official Fed guidance on rate path\
Dispersion of dots = degree of disagreement within the Fed\
Wide dispersion → high uncertainty; tight cluster → strong consensus",
        "current_value": "3.875%",
        "current_value_period": "Median 2026 year-end",
        "current_value_color": "gray",
        "chart_label": "FOMC Member Projections for 2026 Year-End Rate (18 members)",
        "chart_type": "none",
        "chart_data": None,
        "stat1_label": "2026 Median Dot",
        "stat1_value": "3.875%",
        "stat1_sub": "2 × 25 bps cuts",
        "stat1_color": "blue",
        "stat2_label": "Long-Run Rate",
        "stat2_value": "2.875%",
        "stat2_sub": "Neutral / r-star est.",
        "stat2_color": "gray",
        "insight": "10 of 18 members expect only 0–1 cuts in 2026 — more hawkish than markets hoped. The wide dispersion signals genuine uncertainty. Every new inflation or employment print reshuffles the dots. For investors, this means rate-sensitive positions (real estate, utilities, long bonds) face headwinds until the picture clarifies.",
        "source": "Federal Reserve SEP",
        "back_source_label": "Latest · Dec 2025 SEP",
        "back_title": "2026 Rate Path — Member Projections"
    },
    {
        "card_number": 27,
        "category": "Central Banks",
        "term": "QT",
        "full_name": "Quantitative Tightening / Fed Balance Sheet Runoff",
        "definition": "Quantitative Tightening is the Fed's process of shrinking its balance sheet by allowing Treasury bonds and mortgage-backed securities (MBS) to mature without reinvesting the proceeds. It is the opposite of QE (Quantitative Easing), which expanded the balance sheet by purchasing these assets.",
        "context": "QT puts upward pressure on long-term Treasury yields by reducing a major buyer from the market. It's a form of tightening that works independently from rate hikes, making the total policy stance tighter than the FFR alone suggests.",
        "frequency": "Ongoing · $25B/month runoff pace",
        "trend": "down",
        "trend_label": "↓ Shrinking",
        "formula": "QE: Fed buys bonds → adds money to system → lower yields, more credit\
QT: Fed lets bonds mature → removes money from system → upward pressure on yields\
Balance sheet peaked at $9.0T (Apr 2022); now ~$6.8T — reduced by ~$2.2T",
        "current_value": "$6.80T",
        "current_value_period": "Feb 2026 · Total Assets",
        "current_value_color": "blue",
        "chart_label": "Fed Total Assets ($T) — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "QT Pace",
        "stat1_value": "$25B/mo",
        "stat1_sub": "Slowed from $60B/mo peak",
        "stat1_color": "blue",
        "stat2_label": "Peak Balance Sheet",
        "stat2_value": "$9.0T",
        "stat2_sub": "Apr 2022 · Down ~$2.2T",
        "stat2_color": "gray",
        "insight": "QT at $25B/month means less Fed buying of Treasuries — the government must find private buyers for more of its debt. This keeps long-term yields elevated independent of the FFR. When the Fed eventually pauses QT (expected when reserves approach a \"comfortable\" floor), long bonds could rally significantly.",
        "source": "Federal Reserve H.4.1 Release",
        "back_source_label": "Latest · Federal Reserve H.4.1",
        "back_title": "Fed Balance Sheet — Current"
    },
    {
        "card_number": 28,
        "category": "Central Banks",
        "term": "M2",
        "full_name": "M2 Money Supply",
        "definition": "M2 measures the total supply of money in the U.S. economy — physical cash, checking accounts, savings accounts, money market funds, and small CDs. It is the broadest widely-used measure of \"how much money is sloshing around.\"",
        "context": "M2 surged 27% in 2020–21 (COVID stimulus) and then contracted in 2022–23 as the Fed tightened. Its recent re-acceleration to ~4% growth is being watched closely as a potential leading indicator of renewed inflation pressure.",
        "frequency": "Published: Monthly (Federal Reserve H.6)",
        "trend": "up",
        "trend_label": "↑ Re-accelerating",
        "formula": "M1: Cash + checking accounts (most liquid)\
M2: M1 + savings + money market funds + small CDs\
Milton Friedman: \"Inflation is always and everywhere a monetary phenomenon\" — M2 growth predicts inflation with a 12–18 month lag",
        "current_value": "+4.1%",
        "current_value_period": "Feb 2026 · YoY",
        "current_value_color": "red",
        "chart_label": "M2 Money Supply YoY Growth Rate — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "M2 Level",
        "stat1_value": "$21.4T",
        "stat1_sub": "Total money supply",
        "stat1_color": "blue",
        "stat2_label": "COVID Peak Growth",
        "stat2_value": "+27%",
        "stat2_sub": "2021 · drove 2022 inflation",
        "stat2_color": "gray",
        "insight": "M2 growing at 4% after shrinking in 2023 means monetary conditions are easing again. Historically, sustained M2 growth above 5–6% precedes inflation with a 12–18 month lag. This is why monetarist economists are cautious about declaring victory on inflation — money supply says the fight isn't fully won.",
        "source": "Federal Reserve H.6 Release",
        "back_source_label": "Latest · Federal Reserve H.6",
        "back_title": "M2 Year-Over-Year Growth — Current"
    },
    {
        "card_number": 29,
        "category": "Central Banks",
        "term": "SLOOS",
        "full_name": "Senior Loan Officer Opinion Survey on Bank Lending Practices",
        "definition": "Every quarter, the Fed surveys ~80 large U.S. banks and ~24 foreign banks on their lending standards. The key question: are you tightening or easing credit conditions for business loans, mortgages, and consumer credit? The net percentage is the signal.",
        "context": "When banks tighten, businesses struggle to borrow and invest. SLOOS has predicted every recession since the 1990s — a sustained move above +30% net tightening is a reliable red flag. Fed Chair Powell references SLOOS in almost every press conference.",
        "frequency": "Published: Quarterly (Jan, Apr, Jul, Oct)",
        "trend": "flat",
        "trend_label": "→ Easing Slowly",
        "formula": "Net % Tightening = % of banks tightening − % of banks easing\
Positive number → more banks making credit harder to get\
Negative number → more banks loosening credit (stimulative)\
SLOOS leads economic activity by ~6–9 months",
        "current_value": "14.6%",
        "current_value_period": "Q4 2025 · Still net tight",
        "current_value_color": "blue",
        "chart_label": "Net % of Banks Tightening C&I Loan Standards — Quarterly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "C&I Loans Tight",
        "stat1_value": "14.6%",
        "stat1_sub": "Declining from 22.4% peak",
        "stat1_color": "blue",
        "stat2_label": "Consumer Loans Tight",
        "stat2_value": "18.2%",
        "stat2_sub": "Still restrictive",
        "stat2_color": "red",
        "insight": "Still net tightening, but the trend is clearly improving — a positive leading signal. When SLOOS returns to net neutral or easing, it typically precedes a credit expansion cycle 6–9 months later, which benefits small-cap stocks (more bank-dependent) and high-yield bonds. Watch for Q1 2026 survey results in April.",
        "source": "Federal Reserve SLOOS",
        "back_source_label": "Latest · Federal Reserve SLOOS",
        "back_title": "Net % Banks Tightening C&I Standards"
    },
    {
        "card_number": 30,
        "category": "Markets",
        "term": "CAPE",
        "full_name": "Cyclically Adjusted Price-to-Earnings Ratio (Shiller PE10)",
        "definition": "CAPE divides the S&P 500 price by the average of the past 10 years of real (inflation-adjusted) earnings. Developed by Nobel laureate Robert Shiller, it smooths out business cycle volatility to give a cleaner picture of whether stocks are cheap or expensive historically.",
        "context": "CAPE is not a market timing tool — it has been \"elevated\" since the 1990s without predicting exact peak dates. But its long-run predictive power for 10-year returns is well documented: high CAPE → below-average returns over the next decade.",
        "frequency": "Updated: Monthly (Shiller's website)",
        "trend": "up",
        "trend_label": "↑ Elevated",
        "formula": "CAPE = S&P 500 Price ÷ 10-Year Average Real Earnings\
Historical average CAPE: ~17\
CAPE > 30 → historically expensive; low expected 10-year forward returns\
CAPE < 15 → historically cheap; high expected forward returns",
        "current_value": "34.8",
        "current_value_period": "Mar 2026 · ~2× hist. avg",
        "current_value_color": "red",
        "chart_label": "Shiller CAPE — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "Historical Average",
        "stat1_value": "~17",
        "stat1_sub": "1871–present",
        "stat1_color": "gray",
        "stat2_label": "2000 Peak (dot-com)",
        "stat2_value": "44.2",
        "stat2_sub": "All-time high",
        "stat2_color": "gray",
        "insight": "At 34.8 — roughly double the historical average — U.S. equities are priced for perfection. Historical data suggests below-average 10-year returns from this level. This doesn't mean sell everything, but it does argue for diversification: international ETFs (VEA, EEM) trade at far lower CAPE ratios and offer better long-term value.",
        "source": "Robert Shiller / Yale",
        "back_source_label": "Latest · Shiller / Yale",
        "back_title": "Shiller CAPE Ratio — Current"
    },
    {
        "card_number": 31,
        "category": "Markets",
        "term": "Gold",
        "full_name": "Gold Spot Price (XAU/USD)",
        "definition": "Gold is the oldest financial asset and the world's ultimate store of value and safe-haven currency. Its price reflects a combination of inflation expectations, real interest rates, geopolitical stress, central bank demand, and the strength of the U.S. dollar.",
        "context": "Central banks — especially China, India, Poland, and Turkey — have been buying gold at record pace since 2022 as a hedge against U.S. dollar dominance. This structural demand has suppressed gold's typical inverse relationship with rising real rates.",
        "frequency": "Updated: Continuously (global markets)",
        "trend": "up",
        "trend_label": "↑ New Highs",
        "formula": "Gold rises when: real rates fall · dollar weakens · inflation fears rise · geopolitical risk spikes · central banks buy\
Gold falls when: real rates rise · dollar strengthens · risk appetite returns\
Gold has no yield — its opportunity cost is the real interest rate",
        "current_value": "$5,204",
        "current_value_period": "Mar 2026 · All-Time High",
        "current_value_color": "yellow",
        "chart_label": "Gold Price ($/oz) — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "YTD Performance",
        "stat1_value": "+19.6%",
        "stat1_sub": "From ~$4,350 Jan 1",
        "stat1_color": "green",
        "stat2_label": "Central Bank Demand",
        "stat2_value": "Record",
        "stat2_sub": "Structural driver",
        "stat2_color": "yellow",
        "insight": "Gold at all-time highs alongside elevated real rates (which typically suppress gold) is unusual — driven by central bank de-dollarization buying and geopolitical hedging. A 5–10% gold allocation via GLD or IAU provides portfolio diversification; gold's correlation to equities has been near zero over the past decade.",
        "source": "LBMA / Spot Market",
        "back_source_label": "Latest · LBMA / Spot Market",
        "back_title": "Gold — Current Price"
    },
    {
        "card_number": 32,
        "category": "Markets",
        "term": "WTI",
        "full_name": "WTI Crude Oil Price (West Texas Intermediate)",
        "definition": "WTI is the benchmark price for U.S.-produced crude oil, set at trading hubs in Cushing, Oklahoma. It is one of the most widely traded commodities in the world — and because oil touches almost every sector of the economy, its price ripples through inflation, corporate margins, and consumer spending.",
        "context": "Oil price is set by global supply/demand, OPEC+ production decisions, U.S. shale production, geopolitical events, and the strength of the dollar (oil is priced in USD globally). It is one of the most \"noisy\" indicators but also one of the fastest to move.",
        "frequency": "Updated: Continuously (NYMEX)",
        "trend": "flat",
        "trend_label": "→ Stable",
        "formula": "Oil high → gasoline prices rise · transportation costs rise · CPI rises\
Oil low → consumer \"tax cut\" effect · airline, shipping margins improve · but signals weak demand\
Every $10/bbl rise in oil adds approximately 0.2–0.3% to U.S. CPI",
        "current_value": "$70.1",
        "current_value_period": "Mar 2026 · per barrel",
        "current_value_color": "blue",
        "chart_label": "WTI Crude Oil Price ($/bbl) — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "Brent Crude",
        "stat1_value": "$74.2",
        "stat1_sub": "Global benchmark",
        "stat1_color": "blue",
        "stat2_label": "OPEC+ Target",
        "stat2_value": "~$70",
        "stat2_sub": "Production cuts calibrated here",
        "stat2_color": "gray",
        "insight": "Oil near $70 is a Goldilocks level — low enough not to spike CPI, high enough not to signal demand collapse. OPEC+ production cuts are preventing a price drop that would reflect weak global growth. Watch for moves above $85 (inflation risk) or below $60 (demand recession signal) as the levels that would change the macro story.",
        "source": "NYMEX / EIA",
        "back_source_label": "Latest · NYMEX / EIA",
        "back_title": "WTI Crude Oil — Current"
    },
    {
        "card_number": 33,
        "category": "Markets",
        "term": "EPS Growth",
        "full_name": "S&P 500 Earnings Per Share Growth (YoY)",
        "definition": "EPS growth measures how much corporate earnings increased (or fell) compared to the same quarter a year ago. For the S&P 500, it represents the aggregate earnings power of America's 500 largest public companies — the foundation of stock market valuations.",
        "context": "Every quarter, ~500 companies report results over a 4-week earnings season. \"Beats rate\" (% that exceed consensus estimates) and forward guidance matter as much as the actual numbers — stocks are priced on future expectations, not past results.",
        "frequency": "Published: Quarterly (earnings seasons)",
        "trend": "flat",
        "trend_label": "→ Steady",
        "formula": "Stock prices = EPS × P/E multiple\
Earnings drive long-run returns; multiple expansion drives short-run moves\
EPS misses → stocks fall · EPS beats → stocks rally — especially during earnings season",
        "current_value": "+8.2%",
        "current_value_period": "Q4 2025 Blended YoY",
        "current_value_color": "green",
        "chart_label": "S&P 500 EPS Growth YoY — Quarterly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "2026 Consensus Est.",
        "stat1_value": "+11.3%",
        "stat1_sub": "Full-year forecast",
        "stat1_color": "green",
        "stat2_label": "Beats Rate",
        "stat2_value": "74%",
        "stat2_sub": "Above historical avg (67%)",
        "stat2_color": "green",
        "insight": "Eight percent earnings growth despite macro headwinds is solid. Markets are pricing in +11.3% for 2026 — which requires continued economic resilience. If macro softens or tariff costs bite into margins, earnings estimate cuts would likely compress the S&P 500's rich valuation. Watch guidance language in Q1 2026 earnings reports.",
        "source": "FactSet Earnings Insight",
        "back_source_label": "Latest · FactSet Earnings Insight",
        "back_title": "S&P 500 EPS Growth — Current"
    },
    {
        "card_number": 34,
        "category": "Trade & FX",
        "term": "Trade Balance",
        "full_name": "U.S. International Trade in Goods & Services",
        "definition": "The trade balance measures the difference between U.S. exports and imports. When imports exceed exports (the U.S. norm), the result is a trade deficit. The U.S. has run a persistent trade deficit for decades — it is the world's largest goods importer.",
        "context": "The trade deficit is politically charged but economically nuanced. A widening deficit can actually signal a strong economy (consumers buying imported goods). However, tariffs aimed at reducing the deficit often trigger retaliatory actions that hurt U.S. exporters.",
        "frequency": "Published: Monthly (~5th week)",
        "trend": "up",
        "trend_label": "↑ Widening",
        "formula": "Trade Balance = Exports − Imports\
Negative = trade deficit (U.S. buys more from the world than it sells)\
Widening deficit → GDP math drag (net exports subtract from GDP)\
But reflects strong domestic demand — not necessarily a sign of weakness",
        "current_value": "−$131B",
        "current_value_period": "Jan 2026 · Record monthly deficit",
        "current_value_color": "red",
        "chart_label": "U.S. Monthly Trade Balance ($B) — Recent",
        "chart_type": "bar_inverted",
        "chart_data": None,
        "stat1_label": "Goods Deficit",
        "stat1_value": "−$164B",
        "stat1_sub": "Largest component",
        "stat1_color": "red",
        "stat2_label": "Services Surplus",
        "stat2_value": "+$32B",
        "stat2_sub": "Tech, finance, travel",
        "stat2_color": "green",
        "insight": "The record January deficit reflects companies front-loading imports ahead of tariffs — pulling demand forward. This will mechanically drag Q1 2026 GDP growth lower, but it's a distortion, not a signal of fundamental weakness. Expect the deficit to narrow once the pre-tariff rush subsides, which could provide a GDP bounce in Q2.",
        "source": "U.S. Census Bureau / BEA",
        "back_source_label": "Latest · Census Bureau / BEA",
        "back_title": "Trade Balance — Current"
    },
    {
        "card_number": 35,
        "category": "Trade & FX",
        "term": "Tariff Rate",
        "full_name": "U.S. Effective Tariff Rate on Imports",
        "definition": "The effective tariff rate is the average tax the U.S. government collects on all imported goods — calculated as total tariff revenue divided by total import value. It reflects the aggregate impact of all tariff schedules across all trading partners.",
        "context": "The U.S. effective tariff rate averaged ~2.5% for two decades before 2025. The sweeping tariff actions of 2025–26 have pushed it toward levels last seen in the 1930s (Smoot-Hawley era), representing the most significant trade policy shift in nearly a century.",
        "frequency": "Updated: As policy changes",
        "trend": "up",
        "trend_label": "↑ Rising Fast",
        "formula": "Effective Tariff Rate = Tariff Revenue Collected ÷ Total Import Value\
A 10% blanket tariff doesn't raise the effective rate by 10% immediately — some imports are exempt, others face retaliatory tariffs that reduce import volume\
Pass-through to consumers: typically 80–100% within 6–12 months",
        "current_value": "~13.5%",
        "current_value_period": "Mar 2026 · Estimate",
        "current_value_color": "red",
        "chart_label": "U.S. Effective Tariff Rate — Policy Timeline",
        "chart_type": "timeline",
        "chart_data": None,
        "stat1_label": "China Tariff Rate",
        "stat1_value": "54%",
        "stat1_sub": "Highest bilateral rate",
        "stat1_color": "red",
        "stat2_label": "CPI Tariff Impact Est.",
        "stat2_value": "+0.5–1.5%",
        "stat2_sub": "Full pass-through",
        "stat2_color": "red",
        "insight": "Tariffs at these levels are effectively a consumption tax — paid by U.S. importers and passed to consumers. For ETF investors, this means pressure on import-heavy retail and consumer goods companies, and a potential boost for domestic manufacturers. Watch earnings guidance for explicit tariff cost commentary starting in Q1 2026 reports.",
        "source": "PIIE / Tax Foundation / U.S. Customs",
        "back_source_label": "Estimated · PIIE / Tax Foundation",
        "back_title": "Effective Tariff Rate — Current"
    },
    {
        "card_number": 36,
        "category": "Trade & FX",
        "term": "USD/CNY",
        "full_name": "U.S. Dollar vs. Chinese Yuan (Renminbi)",
        "definition": "USD/CNY measures how many Chinese yuan one U.S. dollar buys. A higher number means a weaker yuan (dollar stronger). China's central bank (PBOC) sets a daily \"fixing\" rate and allows the yuan to trade within a ±2% band around it — making this a managed, not freely floating, exchange rate.",
        "context": "The yuan is the global barometer of U.S.–China trade tensions. When tariffs escalate, China often allows controlled yuan depreciation to offset competitiveness losses. Rapid depreciation beyond 7.50 historically triggers EM currency contagion and global risk-off moves.",
        "frequency": "Updated: Daily (managed float)",
        "trend": "flat",
        "trend_label": "→ Watched Closely",
        "formula": "Stronger yuan (lower USD/CNY) → Chinese exports more expensive · easier to import · PBOC loosening\
Weaker yuan (higher USD/CNY) → Chinese exports cheaper · offsets some tariff impact · capital outflow risk\
Offshore CNH rate (freely traded in Hong Kong) often diverges from onshore CNY",
        "current_value": "7.25",
        "current_value_period": "Mar 2026 · CNY per USD",
        "current_value_color": "red",
        "chart_label": "USD/CNY (higher = weaker yuan) — Monthly",
        "chart_type": "bar",
        "chart_data": None,
        "stat1_label": "PBOC Daily Fix",
        "stat1_value": "7.22",
        "stat1_sub": "Slightly stronger than market",
        "stat1_color": "blue",
        "stat2_label": "Risk Threshold",
        "stat2_value": "7.50",
        "stat2_sub": "Beyond here = EM contagion risk",
        "stat2_color": "red",
        "insight": "Yuan at 7.25 is elevated but within managed territory — the PBOC fix at 7.22 signals they're not allowing rapid depreciation. A controlled yuan limits tariff offset for China but preserves financial stability. If USD/CNY breaks 7.50, watch for a broader EM currency sell-off affecting EM ETFs (EEM, VWO) globally.",
        "source": "PBOC / Bloomberg",
        "back_source_label": "Latest · PBOC / Bloomberg",
        "back_title": "USD/CNY Exchange Rate — Current"
    }
]
